name: checkstyle.yml

on: [push,pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Check build with checkstyle.xml
        run: mvn checkstyle:check